# SPDX-FileCopyrightText: 2026 the Sandbox contributors
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "sandbox_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
sandbox_engine = { path = "../sandbox_engine" }
bevy = { workspace = true }
bevy_egui = { workspace = true }
