# SPDX-FileCopyrightText: 2026 the Sandbox contributors
# SPDX-License-Identifier: GPL-3.0-or-later

[workspace]
resolver = "2"
members = [
    "crates/sandbox_engine",
    "crates/sandbox_editor",
    "crates/spaceminer",
]

[workspace.dependencies]
bevy = "0.15"
bevy_egui = "0.31"
