# SPDX-FileCopyrightText: 2026 the Sandbox contributors
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "sandbox_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
serde = "1.0"
